development:
  adapter: postgresql
  database: malvina_dev
  pool: 5
  timeout: 5000
  username: malvina
  password: malvina
test:
  adapter: postgresql
  database: malvina_test
  pool: 5
  timeout: 5000
  username: malvina
  password: malvina

production:
  adapter: postgresql
  database: malvina_prod
  pool: 5
  timeout: 5000
  username: malvina
  password: malvina
